version: '3'
services:
  backend:
    image: "example-login-app"
    ports:
      - "3003:3000"
    environment:
      - JWT_SECRET=my_custom_secret_key
    networks:
      - my_test_network_03

  frontend:
    image: nginx:alpine
    ports:
      - "8083:80"
    volumes:
      - ./app/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - backend
    networks:
      - my_test_network_03

  cypress:
    image: 'example-cypress'
    volumes:
      - ./setup/cypress:/example-cypress/cypress/e2e
    working_dir: /example-cypress
    depends_on:
      - frontend
    networks:
      - my_test_network_03
    command: 'cypress run --config baseUrl=http://frontend:80'

  playwright:
    image: 'example-playwright'
    volumes:
      - ./setup/playwright:/example-playwright/e2e
    environment:
      - BASE_URL=http://frontend:80
    depends_on:
      - frontend
    networks:
      - my_test_network_03
    command: 'npx playwright test --browser=chromium'

networks:
  my_test_network_03:
