version: '3'
services:
  frontend:
    image: 'nginx:alpine'
    ports:
      - '8084:80'
    volumes:
      - ./app:/usr/share/nginx/html:ro
    networks:
      - my_test_network_04

  cypress:
    image: 'example-cypress'
    volumes:
      - ./setup/cypress:/example-cypress/cypress/e2e
    depends_on:
      - frontend
    networks:
      - my_test_network_04
    command: 'cypress run --config baseUrl=http://frontend:80'

  playwright:
    image: 'example-playwright'
    volumes:
      - ./setup/playwright:/example-playwright/e2e
    environment:
      - BASE_URL=http://frontend:80
    depends_on:
      - frontend
    networks:
      - my_test_network_04
    command: 'npx playwright test --browser=chromium'

networks:
  my_test_network_04:
