version: '3'
services:
  web:
    image: 'nginx:1.19-alpine'
    volumes:
      - ./html:/usr/share/nginx/html
    ports:
      - '88:80'
    networks:
      - my-test-network

  cypress:
    image: 'cypress-demo:latest'
    volumes:
      - ./cypress-demo:/cypress-demo
    working_dir: /cypress-demo
    networks:
      - my-test-network
    depends_on:
      - web
    environment:
      - CYPRESS_baseUrl=http://web:80
    command: 'DEBUG=cypress:* cypress run'

#   playwright:
#     image: 'mcr.microsoft.com/playwright:latest'
#     volumes:
#       - ./playwright-demo:/e2e
#     working_dir: /e2e
#     networks:
#       - my-test-network
#     depends_on:
#       - web
#     environment:
#       - baseURL=http://web:80
#     command: 'npx playwright test'

networks:
  my-test-network:
