version: '3'
services:
  web:
    image: 'nginx:alpine'
    volumes:
      - ./html:/usr/share/nginx/html
    ports:
      - '8082:80'
    networks:
      - my_test_network_02

  cypress:
    image: 'cypress-demo'
    volumes:
      - ./tests/cypress:/cypress-demo/cypress/e2e
    working_dir: /cypress-demo
    networks:
      - my_test_network_02
    depends_on:
      - web
    command: 'cypress run --config baseUrl=http://web:80'

  playwright:
    image: 'playwright-demo'
    volumes:
      - ./tests/playwright:/playwright-demo/e2e
    networks:
      - my_test_network_02
    depends_on:
      - web
    environment:
      - BASE_URL=http://web:80
    command: 'npx playwright test --browser=chromium'

networks:
  my_test_network_02:
