version: '3'
services:
  web:
    image: 'nginx:1.19-alpine'
    volumes:
      - ./html:/usr/share/nginx/html
    ports:
      - '83:80'
    networks:
      - my-test-network

  cypress:
    image: 'cypress-demo'
    volumes:
      - ./tests/cypress:/cypress-demo/cypress/e2e
    working_dir: /cypress-demo
    networks:
      - my-test-network
    depends_on:
      - web
    command: 'cypress run'

#   playwright:
#     image: 'playwright-demo'
#     volumes:
#       - ./tests/playwright:/playwright-demo/e2e
#     networks:
#       - my-test-network
#     depends_on:
#       - web
#     command: 'npx playwright test --browser=chromium'

networks:
  my-test-network:
